### ISSUE TITLE
 dhermanns/rpi-nightscout:latest keeps restarting

### ISSUE THREAD

**Issue by Parallello** [dhermanns/rpi-nightscout#10]
_(Hi there. First of all a shoutout to the developer for giving so many people around the world a chance to have this low-cost solution to an otherwise complicated problem. Big thumbs up !)_

I have an RPi 3 that has been hosting a nightscout instance for a friend of mine since last August. 
I noticed the webpage was down this afternoon. The  "dhermanns/rpi-nightscout:latest"-container is stuck in a restart loop.  

I see this in the logfile:

> Setting up new connection to MongoDB
the server/replset/mongos options are deprecated, all their options are supported at the top level of the options object [poolSize,ssl,sslValidate,sslCA,sslCert,sslKey,sslPass,sslCRL,autoReconnect,noDelay,keepAlive,connectTimeoutMS,family,socketTimeoutMS,reconnectTries,reconnectInterval,ha,haInterval,replicaSet,secondaryAcceptableLatencyMS,acceptableLatencyMS,connectWithNoPrimary,authSource,w,wtimeout,j,forceServerObjectId,serializeFunctions,ignoreUndefined,raw,bufferMaxEntries,readPreference,pkFactory,promiseLibrary,readConcern,maxStalenessSeconds,loggerLevel,logger,promoteValues,promoteBuffers,promoteLongs,domainsEnabled,keepAliveInitialDelay,checkServerIdentity,validateOptions,appname,auth]
GIT HEAD 9f7de63
Successfully established a connected to MongoDB
Mongo Storage system ready
/home/node/app/node_modules/mongodb/lib/mongo_client.js:433
          throw err
          ^

> SyntaxError: Error parsing /home/node/app/node_modules/jsonwebtoken/package.json: Unexpected token � in JSON at position 1042
>     at JSON.parse (<anonymous>)
>     at readPackage (module.js:116:52)
>     at tryPackage (module.js:126:13)
>     at Function.Module._findPath (module.js:208:20)
>     at Function.Module._resolveFilename (module.js:525:25)
>     at Function.Module._load (module.js:476:23)
>     at Module.require (module.js:568:17)
>     at require (internal/module.js:11:18)
>     at Object.<anonymous> (/home/node/app/lib/authorization/index.js:4:11)
>     at Module._compile (module.js:624:30)
> 

I will admit I tried an apt-get update && upgrade right before the troubles started. This spits out:
`The following packages have unmet dependencies:
 docker-ce-cli : Breaks: docker-ce (< 5:18.09) but 18.06.1~ce~3-0~raspbian is installed`

Thanks for taking the time to look into this !

**Comment by Parallello** [comment]
Right. I see.

Is it possible to 'extract'  the API-tokens for the different devices that have been allowed access to the website and reuse them on the new installation ? Are they saved in the /var/lib/docker/overlay2/... somewhere ?

**Comment by dhermanns** [comment]
I never tried. Maybe someone else has experience with that?
Parallello <notifications@github.com> schrieb am Sa. 29. Dez. 2018 um 12:56:

**Comment by mallert0** [comment]
Hi, is it possible to upgrade nightscout from 10.3 to 13.0.1 using your way?

**Comment by dhermanns** [comment]
Should be

**Comment by mallert0** [comment]
Should be? But it is still on 0.10.3.1, when i try to reinstall like in your desciption?

**Comment by dhermanns** [comment]
If you modify the Dockerfile it should wird with later versions, too. If you have a look here:
https://hub.docker.com/r/dhermanns/rpi-nightscout/tags

If got it running using nightscout 0.12.4. If I'll find some time, I will update to the latest version...

Did you try to use 0.12.4 instead of latest? I will have to link latest to 0.12.4. Looks like it points to an older version right now.

**Comment by mallert0** [comment]
Tried to update to 0.12.4, what worked for me, but is it possible that there is a forwarding directly to https ? This is not working for me :/ Pulled 0.12.4 but opening then the website didnt work because of https

**Comment by dhermanns** [comment]
No - not from the docker file. All that's done here is:
https://github.com/dhermanns/rpi-nightscout/blob/master/Dockerfile
