### ISSUE TITLE
RasPi Zero (W)?

### ISSUE THREAD

**Issue by steve8x8** [dhermanns/rpi-nightscout#11]
Would this also run on a RPi0(w)? It's supposed to provide a hardware platform almost identical to the RPi1 (perhaps 2), and would be a great space-saver...

**Comment by dhermanns** [comment]
I don’t have one. Just tested with Pi2/3/4.

**Comment by steve8x8** [comment]
Thanks. At least the [Cypriot FAQ](http://blog.hypriot.com/faq/) suggests that Docker would run on a Zero too. I'll try and report back -

**Comment by steve8x8** [comment]
Gosh. That was meant to say "Hypriot" and I seem to be unable to edit it. D*mn autocorrect.

**Comment by dhermanns** [comment]
;-) Thx
