### ISSUE TITLE
BZ-Values

### ISSUE THREAD

**Issue by Harrypatz** [dhermanns/rpi-nightscout#12]
Hello, I did the project once on a Pi 1 and on a Pi 3 according to your description "rpi-nightscout". But on the Pi1 it doesn't work at all, and on the Pi3 it runs, the start page can be opened, the profile has to be edited, but no BZ values are displayed. The only things displayed are manual actions in AAPS. If you shut down the Pi and restart, the page is no longer accessible. Do you know a solution?

Greetings Harry

Translated with www.DeepL.com/Translator (free version)

**Comment by Harrypatz** [comment]
Hello, I did the project once on a Pi 1 and on a Pi 3 according to your description "rpi-nightscout". But on the Pi1 it doesn't work at all, and on the Pi3 it runs, the start page can be opened, the profile has to be edited, but no BZ values are displayed. The only things displayed are manual actions in AAPS. If you shut down the Pi and restart, the page is no longer accessible. Do you know a solution?

Greetings Harry

Translated with www.DeepL.com/Translator (free version)

**Comment by dhermanns** [comment]
Pi1 could be a problem. Didn‘t used it for a long time. If the UI comes up on your Pi3, that looks promising. May be you have a security issue with your nightscout security token. You could try to manually try to upload sgv data using curl.

If the system doesn‘t came up after a Pi restart: Does the docker daemon came up again and is the container auto started?

**Comment by Harrypatz** [comment]
Hello, thanks for the quick answer, I'm pretty inexperienced in Linux. What is sgv-data? And how do I test if the Docker Daemon runs. How do I upload the data via curl?

**Comment by Harrypatz** [comment]
Hello, thanks for the quick answer, I'm pretty inexperienced in Linux. What is sgv-data? And how do I test if the Docker Daemon runs. How do I upload the data via curl?

**Comment by dhermanns** [comment]
Have a look here:

https://github.com/nightscout/cgm-remote-monitor/blob/master/bin/post-sgv.sh

You can see running containers by doing

docker ps

Cu,
Dirk

Harrypatz <notifications@github.com> schrieb am Di. 3. Dez. 2019 um 12:08:
