### ISSUE TITLE
Error connecting to MongoDB

### ISSUE THREAD

**Issue by dassystem** [dhermanns/rpi-nightscout#14]
Hi there,

when running a fresh `docker-compose up`

I get  `Error connecting to MongoDB: {"name":"MongoNetworkError","errorLabels": "TransientTransactionError"]} - retrying in 3 sec`

I'm using a Raspberry Pi 4 - 4GB with…
```
$ uname -a
Linux pi4 4.19.118-v8+ #1311 SMP PREEMPT Mon Apr 27 14:32:38 BST 2020 aarch64 GNU/Linux
```
It might have something to do with my v8+ Kernel, which I got after a recent update. 

I attach my `docker-compose logs`
[docker-ns.log](https://github.com/dhermanns/rpi-nightscout/files/4941511/docker-ns.log)

Do you have any suggestion how to deal with this error? I'm not able to start the application.

**Comment by dhermanns** [comment]
Hi Adrian,

yes - could be. I'm using:

Linux k2 4.19.57-v7l+ #1244 SMP Thu Jul 4 18:48:07 BST 2019 armv7l GNU/Linux


Am Sa., 18. Juli 2020 um 12:58 Uhr schrieb Adrian Salamon <
notifications@github.com>:

**Comment by dassystem** [comment]
I did some research: the v8 kernel is a 64bit system and it seems that it does not like the MonogDB container. I was able to switch back to a 32bit kernel via these instructions (but reverse) https://www.sindastra.de/p/1345/switch-your-raspberry-pi-to-64-bit-kernel-raspbian/ .
