### ISSUE TITLE
cannot connect to server

### ISSUE THREAD

**Issue by DrCR77** [dhermanns/rpi-nightscout#18]
Hi!

thanks for this work! I followed the instructions but get stuck when I try to connect to the server http://x.x.x.x:1337. It simply doesn't exist. 

edit: I realize that it might be connected to the browser, replacing http always with https. Whitelisting it doesn't help. Is there a workaround?

this is what docker ps shows: 

HypriotOS/armv7: pirate@black-pearl in ~/rpi-nightscout
$ docker ps
CONTAINER ID        IMAGE                             COMMAND                  CREATED             STATUS              PORTS                    NAMES
2604de9cc995        dhermanns/rpi-nightscout:latest   "docker-entrypoint.s…"   15 minutes ago      Up 15 minutes       0.0.0.0:1337->1337/tcp   rpinightscout_nightscout_1
a180f24bbb7d        dhermanns/rpi-mongo:2.6.4         "/opt/mongodb/bin/mo…"   15 minutes ago      Up 15 minutes       27017/tcp                rpinightscout_mongo_1
d6899398fc3d        hypriot/rpi-busybox-httpd         "/bin/busybox httpd …"   33 minutes ago      Up 33 minutes       0.0.0.0:80->80/tcp       distracted_wilson

**Comment by ThorstenS-linux** [comment]
The solution is to add `INSECURE_USE_HTTP: "true"` in docker-compose.yml, when you do not provide le-certs.
hth
/thorsten

**Comment by JoebartOOn** [comment]
Hello, 
How to update nightscout from 13.0.1 to 14.0.6? 
It's possible? 
Thanks for your feedback.

**Comment by dhermanns** [comment]
Yes - should be just a version number change. But I currently have no pi in
place to generate a new image. But I will update it (after some time).

JoebartOOn <notifications@github.com> schrieb am So. 1. Nov. 2020 um 16:28:

**Comment by JoebartOOn** [comment]
Can you explain to me how to do it please?

**Comment by dhermanns** [comment]
I pushed a new version. With a little bit of luck, that should do. Right now my current raspi didn't seem to have enough memory to build with node12. But maybe you have a raspi with more than 1GB of memory.

**Comment by JoebartOOn** [comment]
Hi,
I just did all the manipulation, and it's not good.
Thanks for your feedback.

**Comment by dhermanns** [comment]
I bought a new RPI4 with 4GB of RAM and created the new image.
You can now simply pull it from the HUB again:
https://hub.docker.com/r/dhermanns/rpi-nightscout

Works fine for me.
