### ISSUE TITLE
Update for Nightscout 0.9  use Dev branch and including how to set options

### ISSUE THREAD

**Issue by tomasboudr** [dhermanns/rpi-nightscout#2]
This is an awesome ... going to attempt to deploy on a local Pi Zero I have.... 
One issue is for you to make it so that we can grab a newer version of NS and also if in the instructions you could note where the files are that configure NS so that we can set the various options (such as ENABLE Openaps) etc.

**Comment by dhermanns** [comment]
I updated the docker and docker-compose files to use nightscout 0.9.2. The documentation is updated to refer to how nightscout parameters can be passed using the docker-compose.yml.

Please have a look if everything is clear and working for you now. Have fun ;-)

**Comment by tomasboudr** [comment]
You rock!
