### ISSUE TITLE
How to change default settings

### ISSUE THREAD

**Issue by JerryEnt** [dhermanns/rpi-nightscout#22]
How/where can I change the default settings?

**Comment by dhermanns** [comment]
Hi Jerry!

What for a setting do you mean?

**Comment by dhermanns** [comment]
You can change some values in the Alarms Settings of Nightguard. The Units
can be changed on the Preferences Tab.

**Comment by saretas** [comment]
Hallo, wo oder wie kann ich API secret ändern,
ich würde gerne auch das Behanlungportal Aktiviren und auch meine Basalrate eintragen. 

kann man die datei my.env bearbeiten, bzw wo kann ich die finden ?

danke, gruß saretas

Hello, where or how can I change API secret,
I would also like to enter the activation portal and my basal rate.

can you edit the my.env file, or where can I find it?

thank you, greetings saretas

**Comment by dhermanns** [comment]
Hi,

You can change the API Secret here:

https://github.com/dhermanns/rpi-nightscout/blob/master/docker-compose.yml#L5

**Comment by dhermanns** [comment]
Careportal can be enabled here:

https://github.com/dhermanns/rpi-nightscout/blob/master/docker-compose.yml#L16
