### ISSUE TITLE
Combining this with Jamorham's RPi/USB Wixel setup

### ISSUE THREAD

**Issue by benhami1ton** [dhermanns/rpi-nightscout#3]
Hey! First of all, thanks for the hard work of developing and maintaining this!
I'm working towards the goal of using a Pi 3b and a USB wixel to grab the G4 cgm data, then deposit that data into the MongoDB that is created using the docker application you've built, so that we can run Nightscout and access it remotely. 

Jamorham's setup connects to an Android device working as the uploader with xDrip installed. I'm trying to keep everything isolated to the Pi, since this doesn't need to be portable.

Is this possible? Am I properly understanding what your project does, and do you know of anyone else doing it this way?
Thanks! -Ben

**Comment by dhermanns** [comment]
Hi Ben! Yes - this is more or less the same I'm doing with it. I'm using a different CGM and Uploader but my Uploader loads to my isolated Pi running rpi-nightscout and rpi-mongo.

So with this docker-compose file, you should have all you need for an isolated nightscout setup.

**Comment by benhami1ton** [comment]
So if I'm already receiving the raw data onto the Pi from the CGM, if I don't have an uploader device, can I just feed that data back into the same Pi running rpi-nightscout and rpi-mongo, and skip the uploader altogether? Or do I have to still have some device running the xdrip application to serve as the interpreter of the raw data that also uploads it to a DB(either in the cloud or on the Pi)?

Apologies on so many questions! I'm trying to learn as I go. Based on what you've said, it seems I'm going to need an uploader of some sort, regardless of whether I host Nightscout in the cloud or host it on the Pi. Is that an accurate conclusion?

Thank you so much for the quick reply! This is for my T1D wife and I'm trying to set this up before I leave on a long trip out of town, so I greatly appreciate your help. :)

**Comment by dhermanns** [comment]
No problem - my pleasure to hopefully help!  And yes - the easiest way is to still use some uploader. I was always wanting to get the pi completely self contained and even run the uploader on the pi. I know that others already doing this, but didn't had the time to integrate it yet.

Have a lock at the great work of Ben West and others regarding the [openaps toolbelt](https://github.com/openaps/docs). There are some python scripts that can be used to decode the raw data and upload to the rpi-nightscout instance.

But as mentioned before - the easiest way would be to configure the uploader to upload to your pi.

**Comment by benhami1ton** [comment]
Awesome. Thanks so much! I'll definitely check that out. In the short term, I guess a cheap Android phone is easier than merging 3 different developers' projects together. ;)

**Comment by dhermanns** [comment]
Yes - absolutely ;-) . And if you would like to have your android up and running 24/7, check out my setup with an y-cable I described [here](https://medium.com/@h3rmanns/constantly-loading-my-nightscout-uploader-with-an-y-cable-813f70da4ccd).
