### ISSUE TITLE
Manifest unknown

### ISSUE THREAD

**Issue by jellevanamstel** [dhermanns/rpi-nightscout#30]
I'm running latest Raspberry Pi OS and I've installed docker, docker-compose and rpi-nightscout, however when running `docker-compose -f docker-compose.armv7.yml up -d` I get the error `manifest for dhermanns/rpi-mongo:2.6. not found: manifest unknown: manifest unknown`

I'm guessing this has to with armv7 (32 bit)?

**Comment by dhermanns** [comment]
Not sure, but you should follow my latest guide:

https://h3rmanns.medium.com/creating-a-k3s-raspberry-pi-cluster-with-k3sup-to-fire-up-a-nightscout-backend-service-based-on-a-27c1f5727e5b

Nightscout now needs a newer mongo-db version and thats adressed by my tutorial above.

**Comment by jellevanamstel** [comment]
Thank you very much for your reply, I overlooked that link by reading too fast apologies.
