### ISSUE TITLE
Error response from daemon

### ISSUE THREAD

**Issue by sh1d0wg1m3r** [dhermanns/rpi-nightscout#33]
![Screenshot 2022-09-07 112342](https://user-images.githubusercontent.com/97878954/188829965-676fb81b-933e-40fe-a594-f83ec584bed6.png)
![Screenshot 2022-09-07 112722](https://user-images.githubusercontent.com/97878954/188830010-4c7169f1-14d5-4dd1-89da-6d68d64c7913.png)
I am using armbian arm64. I tried by default and when I delete the mongo part this happens:
![Screenshot 2022-09-07 113124](https://user-images.githubusercontent.com/97878954/188830818-67836521-e069-4a9d-927d-b2c683da512b.png)
sorry for bad English if any (i am bulgarian)

**Comment by dhermanns** [comment]
Looks like your local directory on your pi is not
/home/pi/docker/rpi-nightscout.

To operate this image, it is highly recommended to NOT use docker-compose,
but kubernetes as a platform.
Have a look at my tutorial here:
https://h3rmanns.medium.com/creating-a-k3s-raspberry-pi-cluster-with-k3sup-to-fire-up-a-nightscout-backend-service-based-on-a-27c1f5727e5b

Am Mi., 7. Sept. 2022 um 10:34 Uhr schrieb sh1d0wg1m3r <
***@***.***>:
