### ISSUE TITLE
Using existing certificate

### ISSUE THREAD

**Issue by latrine666** [dhermanns/rpi-nightscout#34]
Hi,
Iam trying to use an already existing ssl certificate from rapidssl. But if iam entering the path to the private key and full server chain I cannot access nightscout anymore.
The site isn’t available, but in docker container ls the port is opened. 
do you know what’s wrong ?

**Comment by dhermanns** [comment]
Sorry - no. Could have a lot of reasons.
You could try to check your certificate e.g. by ssllabs.

latrine666 ***@***.***> schrieb am Fr. 14. Okt. 2022 um 10:22:

**Comment by latrine666** [comment]
Ok, thanks for the answer !
