### ISSUE TITLE
Upload not possible from xDrip+ / Glimp

### ISSUE THREAD

**Issue by majatocaha** [dhermanns/rpi-nightscout#4]
I set up nightscout just as in the instructions described. I can access it via browser perfectly fine, but if I try to upload it by xDrip+ the error says "Please ensure careportal plugin is enablen on nightscout for treatment upload". I checked already and even gave all permissions to role "careportal", but no effect. I provide the address in this format: http://<api_secret>@<ip_address>:1337/api/v1/

The format in the instructions causes xDrip+ to show an error message about invalid format/characters. The API consists of legal characters only.

When providing Glimp with the address and the API, it says "Not Found!".

**Comment by majatocaha** [comment]
Oh my, nvm, I just had enable the plugin before deplyoing nightscout. Sorry for the inconvenience...

**Comment by dhermanns** [comment]
welcome ;-)
majatocaha <notifications@github.com> schrieb am Do. 6. Juli 2017 um 20:24:

**Comment by bcdiabetes** [comment]
I have the same problem; I have tried enabling CarePortal, but upon clicking "Test Connection", I see the prompt "Not Found".

**Comment by dhermanns** [comment]
Hi!

You should try to drill the problem down by trying to manually post data to
your nightscout backend.

Have a look e.g. here:

https://github.com/nightscout/cgm-remote-monitor/blob/master/testing/populate_rest.js

bcdiabetes <notifications@github.com> schrieb am Di. 25. Feb. 2020 um 01:20:

**Comment by bcdiabetes** [comment]
Hi 

Thank you for your response. I apologise for my rudimentary programming skills. How does one "manually post data" to Nightscout's "backend"?

**Comment by dhermanns** [comment]
You can do that with the HTTP Tool you like. Using Linux you can use curl
or wget to do a http post.

bcdiabetes <notifications@github.com> schrieb am Di. 25. Feb. 2020 um 21:08:

**Comment by bcdiabetes** [comment]
Thank you. I will attempt this and let you know if it worked.
