### ISSUE TITLE
missing Doku: How to connect to the mongo-container from the LAN.

### ISSUE THREAD

**Issue by jroth-haj** [dhermanns/rpi-nightscout#5]
To use nightscoutuploader and openaps, I need to remote connect to the mongo-db.
How can I do that?

**Comment by dhermanns** [comment]
Could you elaborate a bit more what your setup is?

I'm using rpi-Nightscout with the mmcommander uploader which supports the Rest-API to upload data.

So I have no need to directly access the mongo db directly (but that shouldn't be a big deal either)...

**Comment by jroth-haj** [comment]
I run Nightscout and Mongodb as docker image on my raspi.
Now I want use NightscoutUploader to acces the DB and also to download or
edit the data. Please have a look to NightscoutUploader.

Am 28.08.2017 22:04 schrieb "dhermanns" <notifications@github.com>:

**Comment by dhermanns** [comment]
Do you have a link? There are a lot of uploaders out there for the different possible Nightscout setups.

**Comment by jroth-haj** [comment]
So sorry, I mean NightscoutLoader:
https://github.com/gh-davidr/NightscoutLoader/blob/master/README.md

Am 28.08.2017 22:15 schrieb "dhermanns" <notifications@github.com>:

**Comment by dhermanns** [comment]
I didn't use this tool but it looks great. As far as I can see the problem is that it would like to connect directly to the mongo db. So you have to open up the mongo db port in docker.

If I find some time next weekend I will try to setup nightscout loader in my environment.

**Comment by dhermanns** [comment]
I didn't find the time to test this on my own, by I added a part describing how to open the mongoldb ports. Have a look and let me know if this works for you now.
