### ISSUE TITLE
Installation issue with Rpi 1

### ISSUE THREAD

**Issue by F5OEO** [dhermanns/rpi-nightscout#6]
Thx for this simple installation docker. 
Using the same instructions : 
- On rpi1 : 

> nightscout_1 | Error connecting to MongoDB: {"name":"MongoError","message":"connect EHOSTUNREACH 172.17.0.3:27017"} - retrying in 51 sec

- On Rpi 2 : No issue. 
Could be HypriotOS armv6 vs armv7 difference.

**Comment by dhermanns** [comment]
Yes - this is s known Limitation
