### ISSUE TITLE
Update to Nightscout 0.10.3.1

### ISSUE THREAD

**Issue by dassystem** [dhermanns/rpi-nightscout#8]
[Nightscout](https://github.com/nightscout/cgm-remote-monitor) has version 0.10.3.1 by now. This docker image is still on 0.10.1 (mid 2017). Since this is by far the easiest installation of nightscout in the pi, we should update.

Since I have no experience with docker how could I help here?

**Comment by dhermanns** [comment]
Hi! You can try the new Tag I created for you:
https://hub.docker.com/r/dhermanns/rpi-nightscout/tags/

Let me know if that helps...

**Comment by dassystem** [comment]
Thank you!
After `git pull` I ran `docker-compose stop`, `docker-compose pull` and `docker-compose up -d` and it worked out of the box.

**Comment by dhermanns** [comment]
Good to hear - thanks for the feedback
Adrian Salamon <notifications@github.com> schrieb am Mi. 5. Dez. 2018 um
21:02:
