### ISSUE TITLE
After reboot rpinightscout_mongo_1 keeps restarting

### ISSUE THREAD

**Issue by harmen91** [dhermanns/rpi-nightscout#9]
Hi dhermanns,

rpinightscout_mongo_1 keeps restarting

Everything works fine on the first install, but after a reboot nightscout is unable to connect to the database it seems

docker ps:
Restarting (100) 46 seconds ago       rpinightscout_mongo_1

Thanks for your amazing work btw

**Comment by harmen91** [comment]
Allright thanks for the reply. That method seems to work for now.

**Comment by dhermanns** [comment]
Great - and merry xmas!

**Comment by harmen91** [comment]
Thanks you 2
